package com.derivedmed.proj.dao;

import com.derivedmed.proj.model.User;
import com.derivedmed.proj.util.rsparser.ResultSetParser;

import java.lang.reflect.InvocationTargetException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class UserDao implements CrudDao<User> {

    private User user;

    @Override
    public int create(User user) {
        int autoGeneratedId = 0;
        if (!checkUser(user)) {
            try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
                 PreparedStatement preparedStatement = connectionProxy
                         .prepareStatement("INSERT INTO users (role_id, email, password) VALUES (?, ?, ?)", Statement.RETURN_GENERATED_KEYS)) {
//            preparedStatement.setInt(1, user.getId());
                preparedStatement.setInt(1, user.getRole_id());
                preparedStatement.setString(2, user.getEmail());
                preparedStatement.setString(3, user.getPassword());
                preparedStatement.executeUpdate();
                ResultSet id = preparedStatement.getGeneratedKeys();
                id.next();
                autoGeneratedId = id.getInt(1);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return autoGeneratedId;
    }

    @Override
    public User getByID(int id) throws NoSuchMethodException, InvocationTargetException {
        User user = new User();
        String SQL = "SELECT * from users where user_id = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(SQL)) {
            preparedStatement.setInt(1, id);
            ArrayList<User> resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), user);
            if (resultList.size() != 0) {
                user = resultList.get(0);
            } else {
                System.out.println("No user with such id");
            }
        } catch (SQLException | IllegalAccessException | InstantiationException e) {
            e.printStackTrace();
        }
        return user;
    }

    @Override
    public boolean update(User user) {
        String SQL = "UPDATE users SET email = ?, password = ?, role_id = ? WHERE user_id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SQL)) {

            preparedStatement.setString(1, user.getEmail());
            preparedStatement.setString(2, user.getPassword());
            preparedStatement.setInt(3, user.getRole_id());
            preparedStatement.setInt(4, user.getId());
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            return true;
        }
        return false;
    }

    @Override
    public boolean delete(int id) {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("delete from users where user_id =?")) {
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }
    public void createUser(User user) {
        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fp_db","root","root");
            connection.setAutoCommit(false);
            connection.setTransactionIsolation(Connection.TRANSACTION_READ_UNCOMMITTED);
            PreparedStatement preparedStatement = connection.prepareStatement("Select * from users where email =?");
            preparedStatement.setString(1,user.getEmail());
            ResultSet resultSet = preparedStatement.executeQuery();
            if (!resultSet.next()){
                PreparedStatement preparedStatement1 = connection.prepareStatement("insert into users (role_id,email,password,rating) values (?,?,?,?)");
                preparedStatement1.setInt(1,user.getRole_id());
                preparedStatement1.setString(2,user.getEmail());
                preparedStatement1.setString(3,user.getPassword());
                preparedStatement1.setInt(4,user.getRating());
                preparedStatement1.executeUpdate();
                connection.commit();
                preparedStatement.close();
                preparedStatement1.close();
                connection.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    @Override
    public List<User> getAll() throws NoSuchMethodException, InvocationTargetException {
        ArrayList<User> resultList = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("select * from users")) {
            Object parserResult = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), User.class);
            if (parserResult instanceof User) {
                resultList.add((User) parserResult);
            } else {
                resultList = (ArrayList<User>) parserResult;
            }
        } catch (SQLException | IllegalAccessException | InstantiationException e) {
            e.printStackTrace();
        }
        return resultList;
    }

    @Override
    public boolean clearAll() {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             Statement statement = connectionProxy.createStatement()) {
            statement.executeUpdate("DELETE FROM users");
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }

    public boolean checkUser(User user) {
        boolean result = false;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("select * from users where email = ?")) {
            preparedStatement.setString(1, user.getEmail());
            result = preparedStatement.executeQuery().next();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return result;
    }

    public boolean registerUserToReport(int user_id, int report_id) {
        try {
            try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
                 PreparedStatement preparedStatement = connectionProxy.prepareStatement("insert into users_reports (user_id, report_id) values(?, ?)")) {
                preparedStatement.setInt(1, user_id);
                preparedStatement.setInt(2, report_id);
                preparedStatement.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }

    public List<User> getSpeakersByRating() throws NoSuchMethodException, InvocationTargetException {
        ArrayList<User> resultList = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("select * from users where role_id = ? order by rating desc")) {
            preparedStatement.setInt(1, 2);
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException | IllegalAccessException | InstantiationException e) {
            e.printStackTrace();
        }
        return resultList;
    }
}
